### ISSUE TITLE
add support for multi-select option-set queries 

### ISSUE THREAD

**Issue by mojobec** [Chorus/LinqToFetch#2]
multi-select optionsets supports two new condition operators `contain-values` and `not-contain-values`
[multi-select option-set](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/multi-select-picklist)

**Comment by aronmek** [comment]
Completed with [this commit](https://github.com/Chorus/LinqToFetch/commit/b1e75bf8c1b444764cbc519196d67c4ac29db3bc)
