### ISSUE TITLE
Count does not seem to work

### ISSUE THREAD

**Issue by Cherepoc** [Chorus/LinqToFetch#6]
Hello! I'm using this lib in my project to connect to web api crm. I've discovered that count query is not generated correctly.
```
      IQueryable<UserEntity> whereQuery = _context.GetEntityCollection<UserEntity>();
      whereQuery = whereQuery.Where(x => x.UserId == queryOptions.Id);
      whereQuery = whereQuery.Where(x => x.EmailAddress == queryOptions.EmailAddress);
      whereQuery = whereQuery.Where(x => x.Password == queryOptions.Password);
      var a = whereQuery.Count();
```
It generates fetchXml without aggregate column. I traced the bug down to ProjectionBuilder. In the constructor there's this code:
```
            // There won't be any select call in some cases, for example only where
            if (Body == null)
            {
                Type t = e.Type;

                if (t.IsGenericType)
                {
                    Type queryable = t.GetInterface(typeof(IQueryable<>).Name);
                    t = t.GetGenericArguments().First();
                }

                Body = CreateCrmObjectAccess(t, null);
                _stmt.Entity.Columns.AllColumns = true;
            }
```
It gets executed and query loses aggregate column. I'm new to this and not shure how to fix this without breaking up other things.

Also this scenario does not work:
`var count = provider.CreateQuery<contact>().Count();`
The execution process is in recursion indefinitely.

Thanks!

**Comment by aronmek** [comment]
Thanks @Cherepoc for reporting this bug in such detail!
I just released a new version which should fix this issue.
