### ISSUE TITLE
Can't get navigation entity value

### ISSUE THREAD

**Issue by Cherepoc** [Chorus/LinqToFetch#8]
Hello! Me again, using this lib in my project to connect to web api crm (by the way, I think I can share the web api code with you, maybe that will speed up the development of web api part). Anyway, I discovered navigation property values are not handled by the library. The reason for that is that the returned value is returned with property name formatted like $"_{propertyName}_value".
Got this returned:
"_dc_menupresetid_value": "f870ca06-0900-e111-ba65-00155d0a0205"
Property name is dc_menupresetid

**Comment by mojobec** [comment]
thanks for the interest in LinqToFetch!
at the moment we are busy with other stuff, therefore we don't have the time to invest in adding support for web API, but it's definitely something we want to have (specially for .NET core solutions).
feel free to create a PR for the web api.
